name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        override: true
        profile: minimal

    - name: Build rust doc
      run: cargo doc --all-features --no-deps
      env:
        RUSTDOCFLAGS: "--cfg docsrs"

  build:

    strategy:
      matrix:
        rust: [
          1.63.0,
          stable,
          nightly
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust }} with wasm32
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        target: wasm32-unknown-unknown
        profile: minimal

    - uses: Swatinem/rust-cache@v2.7.0

    - name: Base build
      run: cargo build --verbose

    - name: Build with feature 'check'
      run: cargo build --verbose --features check

    - name: Build with feature 'stream'
      run: cargo build --verbose --features stream

    - name: Build full features
      run: cargo build --verbose --all-features

    - name: Build wasm with check feature
      run: cargo build --verbose --target wasm32-unknown-unknown --no-default-features --features check

  test:

    strategy:
      matrix:
        rust: [
          stable,
          nightly
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v2.7.0

    - run: cargo test --verbose --all-features
